# Despliegue automático de las aplicaciones al hacer commits en las ramas main y demo
# La rama MAIN se despliega en produccion (aplicacion que se usa en el centro)
# La rama DEMO es una rama espejo para hacer pruebas de nuevas funcionalidades
# PRIMERO SE MERGEA EN DEMO Y LUEGO DEMO SE PASA A MAIN, NUNCA AL REVÉS (puedes cargarte la app de producción)

name: Deploy Frontend via FTP (main & demo)

on:
  push:
    branches:
      - main
      - demo

jobs:
  build-and-deploy:
    name: Build Angular y subir a FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Verificar versiones
        run: |
          node --version
          npm --version

      - name: Instalar dependencias
        run: npm install

      - name: Configurar environment.prod.ts según entorno
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "Configurando entorno para PRODUCCIÓN"
            cat > src/environments/environment.prod.ts << EOF
          export const environment = {
            production: true,
            api: {
              baseUrl: 'https://aplicaciones.esvirgua.com/reservas-libros/evg-reservas-libros-back/api',
              loginUrl: 'https://aplicaciones.esvirgua.com/reservas-libros/evg-reservas-libros-back/api/login',
            },
            auth: {
              cookieTokenName: 'RDLEVGTKN',
            },
            pathImg: 'assets/img/',
            googleClientId: '660176374148-klpm52u3brlqsmpjvqci3ruk5qk1ofnl.apps.googleusercontent.com'
          };
          EOF
          else
            echo "Configurando entorno para DEMO"
            cat > src/environments/environment.prod.ts << EOF
          export const environment = {
            production: true,
            api: {
              baseUrl: 'https://aplicaciones.esvirgua.com/reservas-libros/evg-reservas-libros-back-demo/api',
              loginUrl: 'https://aplicaciones.esvirgua.com/reservas-libros/evg-reservas-libros-back-demo/api/login',
            },
            auth: {
              cookieTokenName: 'RDLEVGTKN',
            },
            pathImg: 'assets/img/',
            googleClientId: '660176374148-klpm52u3brlqsmpjvqci3ruk5qk1ofnl.apps.googleusercontent.com'
          };
          EOF
          fi

      - name: Modificar app-routing.module.ts para usar HashLocationStrategy
        run: |
          sed -i "s/imports: \[RouterModule.forRoot(routes)\],/imports: \[RouterModule.forRoot(routes, { useHash: true })\],/" src/app/app-routing.module.ts

      - name: Instalar Angular CLI globalmente
        run: npm install -g @angular/cli@14.2.13

      - name: Build Angular
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            ng build --configuration=production --base-href=/reservas-libros/evg-reservas-libros/
          else
            ng build --configuration=production --base-href=/reservas-libros/evg-reservas-libros-demo/
          fi

      - name: Crear archivo .htaccess
        run: |
          cat > dist/evg-reservas-libros-front/.htaccess << EOF
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /
            RewriteRule ^index\.html$ - [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule . index.html [L]
          </IfModule>
          EOF

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ github.ref == 'refs/heads/main' && '/public_html/reservas-libros/evg-reservas-libros/' || '/public_html/reservas-libros/evg-reservas-libros-demo/' }}
          local-dir: ./dist/evg-reservas-libros-front/